### ISSUE TITLE
[fabio_viewer] Fail to display msk files

### ISSUE THREAD

**Issue by vallsv** [silx-kit/fabio#111]
It should be investigated

```
valls@linkdick:/workspace/valls/pyfai.git/test_calibration$ fabio_viewer sample-1/mask.msk
/home/valls/.local/lib/python2.7/site-packages/matplotlib/colors.py:859: RuntimeWarning: invalid value encountered in true_divide
  resdat /= (vmax - vmin)
Traceback (most recent call last):
  File "/usr/bin/fabio_viewer", line 1505, in <module>
    main()
  File "/usr/bin/fabio_viewer", line 1499, in main
    form.open_data_series(args.images)
  File "/usr/bin/fabio_viewer", line 188, in open_data_series
    self.select_new_image(None, imgID=0)
  File "/usr/bin/fabio_viewer", line 822, in select_new_image
    self.on_draw()
  File "/usr/bin/fabio_viewer", line 848, in on_draw
    self.canvas.draw()
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 176, in draw
    FigureCanvasAgg.draw(self)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/image.py", line 495, in draw
    renderer, renderer.get_image_magnification())
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/image.py", line 719, in make_image
    unsampled=unsampled)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/image.py", line 411, in _make_image
    self.get_filternorm() or 0.0, self.get_filterrad() or 0.0)
ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short, float32 or float64
```

**Comment by kif** [comment]
On Tue, 14 Mar 2017 01:39:43 -0700
Valentin Valls <notifications@github.com> wrote:

> It should be investigated
> 
> ```
> valls@linkdick:/workspace/valls/pyfai.git/test_calibration$ fabio_viewer sample-1/mask.msk
> /home/valls/.local/lib/python2.7/site-packages/matplotlib/colors.py:859: RuntimeWarning: invalid value encountered in true_divide
>   resdat /= (vmax - vmin)

It works for me on a "stock" debian8 ... it rather looks like a regression in matplotlib2

lintaillefer:~ % fabio_viewer /usr/share/fabio/testimages/face.msk
/usr/lib/python2.7/dist-packages/matplotlib/colors.py:926: RuntimeWarning: invalid value encountered in true_divide
  resdat /= (vmax - vmin)

-- 
Jérôme Kieffer
tel +33 476 882 445
