### ISSUE TITLE
[build]  fail to build without third_party

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#150]
Hello here the failure when the third_party directory was removed.

I: pybuild base:184: python2.7 setup.py config 
INFO:fabio.setup:Use setuptools
Traceback (most recent call last):
  File "setup.py", line 717, in <module>
    setup_package()
  File "setup.py", line 712, in setup_package
    setup_kwargs = get_project_configuration(dry_run)
  File "setup.py", line 660, in get_project_configuration
    config = configuration()
  File "setup.py", line 249, in configuration
    config.add_subpackage(PROJECT)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "fabio/setup.py", line 39, in configuration
    config.add_subpackage('third_party')
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
    caller_level = 2)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 963, in get_subpackage
    caller_level = caller_level+1)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 745, in __init__
    raise ValueError("%r is not a directory" % (package_path,))
ValueError: 'fabio/third_party' is not a directory
E: pybuild pybuild:283: configure: plugin distutils failed with: exit code=1: python2.7 setup.py config 
dh_auto_configure: pybuild --configure -i python{version} -p 2.7 returned exit code 13
debian/rules:7: recipe for target 'build-arch' failed
make: *** [build-arch] Error 25
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
--------------------------------------------------------------------------------
Build finished at 2017-09-03T11:37:24Z

**Comment by picca** [comment]
Ok understood, I need to remove only the _local dir.

thanks

**Comment by vallsv** [comment]
Yes you have to delete `third_party/_local`. As it is done for `silx`.
