### ISSUE TITLE
cbfimage dies on _loop constructs

### ISSUE THREAD

**Issue by ebknudsen** [silx-kit/fabio#188]
As reported by E. Chan, cbfimage dies on open in _read_cif_header 
with the error:
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/fabio/openimage.py", line 138, in openimage
    obj = obj.read(obj.filename, frame)
  File "/usr/lib/python2.7/dist-packages/fabio/cbfimage.py", line 236, in read
    self._readheader(infile)
  File "/usr/lib/python2.7/dist-packages/fabio/cbfimage.py", line 122, in _readheader
    self._read_cif_header(inStream)
  File "/usr/lib/python2.7/dist-packages/fabio/cbfimage.py", line 164, in _read_cif_header
    self.header[key] = (self.cif[key].strip(" \"\n\r\t"))
AttributeError: 'list' object has no attribute 'strip'
````
This wpould appear to be caused by the fact that the file he's trying to open uses the _loop construct. This causes the value to return a list.

**Comment by vallsv** [comment]
Hi Erik. Thanks for the feedback.

Could you please send use a sample creating this error? Like this we can improve our regression tests.

BTW did you try with Python 3?

**Comment by vallsv** [comment]
Oh, BTW, it looks to be something else than `fabio 0.6.0`, did you try the last version? or the master version? Which version did you use?

**Comment by ebknudsen** [comment]
Sure - no problem I'll just drop what I got from Eric Chan.
I did try with python3, which gave me different error:
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/fabio/openimage.py", line 138, in openimage
    obj = obj.read(obj.filename, frame)
  File "/usr/local/lib/python3.6/dist-packages/fabio/cbfimage.py", line 234, in read
    self._readheader(infile)
  File "/usr/local/lib/python3.6/dist-packages/fabio/cbfimage.py", line 122, in _readheader
    self._read_cif_header(inStream)
  File "/usr/local/lib/python3.6/dist-packages/fabio/cbfimage.py", line 154, in _read_cif_header
    self.cif._parseCIF(header_data)
  File "/usr/local/lib/python3.6/dist-packages/fabio/cbfimage.py", line 480, in _parseCIF
    loopone, length, keys = CIF._analyseOneLoop(fields, i)
  File "/usr/local/lib/python3.6/dist-packages/fabio/cbfimage.py", line 630, in _analyseOneLoop
    for i in range(len(data) / len(keys)):
TypeError: 'float' object cannot be interpreted as an integer
````
but that looks like a different bug altogether.

I could patch the cbfimage code myself to handle loops, but It'll likely be a few days.
[35_HCB_03_01_00001.cbf.gz](https://github.com/silx-kit/fabio/files/1651712/35_HCB_03_01_00001.cbf.gz)

**Comment by ebknudsen** [comment]
Oh dang - I used (out of bad old habits I supposed) the bleeding edge version from the development tree.

**Comment by vallsv** [comment]
Interesting :-) That's the change of the behaviour of `/` between Python 2 and 3.

This should be fix the problem.
```
for i in range(int(len(data) / len(keys))):
```

**Comment by vallsv** [comment]
I can confirm we have the same problem on the master then something have to be fixed.
I have to talk with Jerome, let us try first if it is very easy to fix, else patch are anyway welcome.

**Comment by ebknudsen** [comment]
... and I can confirm that the int(...) fix did fix the "other" issue on python3. The problem is now the same.

**Comment by vallsv** [comment]
Here is a fix https://github.com/silx-kit/fabio/pull/189

Let us know if the result is what you expect. Else patch are anyway welcome.

**Comment by ebknudsen** [comment]
Ok - this loads the file at least, so I'm happy with it. I haven't tested writing the file though.

**Comment by vallsv** [comment]
I check it with Jerome. As result the header is anyway not interpreted as expected. But if you dont need it it's fine.
I have to work on that. And it is important for the writing part.
