### ISSUE TITLE
tests fail on PPC64le (here Python 3.6)

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#247]
```ERROR: test_read (fabio.test.testdm3image.TestDm3Image)
check we can read dm3 images
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gpfs16l/pwrhome/rech/grpgen/uwk35yz/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/test/testdm3image.py", line 79, in test_read
    obj1.read(fname)
  File "/gpfs16l/pwrhome/rech/grpgen/uwk35yz/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/dm3image.py", line 129, in read
    self.read_tag_entry()
  File "/gpfs16l/pwrhome/rech/grpgen/uwk35yz/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/dm3image.py", line 180, in read_tag_entry
    value = self.read_tag_type()
  File "/gpfs16l/pwrhome/rech/grpgen/uwk35yz/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/dm3image.py", line 214, in read_tag_type
    return self.readbytes(read_no_bytes, fmt, swap=self.swap)
  File "/gpfs16l/pwrhome/rech/grpgen/uwk35yz/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/dm3image.py", line 147, in readbytes
    data = numpy.frombuffer(raw, format).copy()
ValueError: buffer size must be a multiple of element size
```

**Comment by kif** [comment]
Beside this, all other tests are passing

**Comment by kif** [comment]
It turns out the test data file was corrupted on Ouessant.
