### ISSUE TITLE
Issue with python3.7 fabio wheel

### ISSUE THREAD

**Issue by t20100** [silx-kit/fabio#259]
The following issue is raised with python3.7, fabio 0.7.0 installed from pypi wheel on Windows:

```
>>> import fabio
>>> f = fabio.open("XXX.edf")
Traceback (most recent call last):
  File "py37env\lib\site-packages\fabio\openimage.py", line 223, in _openimage
    obj = fabioformats.factory(klass_name)
AttributeError: module 'fabio.fabioformats' has no attribute 'factory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py37env\lib\site-packages\fabio\openi
mage.py", line 142, in openimage
    obj = _openimage(filename)
  File "py37env\lib\site-packages\fabio\openimage.py", line 226, in _openimage
    raise IOError("Filename %s can't be read as format %s" % (filename, klass_name))
OSError: Filename XXX.edf can't be read as format edfimage
```

**Comment by t20100** [comment]
This issue does not occurs when installing fabio 0.7.0 from the source tarball

**Comment by kif** [comment]
Will be fixed the new release.
