### ISSUE TITLE
build_doc --> sphinx program output is incrimated

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#292]
Fails recently on debian9

**Comment by kif** [comment]
May be a regression of sphinx between debian9 (1.4.9-2) and debian 9 backports 1.7.9-1~bpo9+1

**Comment by vallsv** [comment]
You dont have output?

**Comment by kif** [comment]
I did not manage to reproduce it on another computer... probably a fishy installation

**Comment by kif** [comment]
```
#   reading sources... [  9%] Changelog
#   reading sources... [ 18%] api/modules
#   reading sources... [ 27%] coverage
#   reading sources... [ 36%] getting_started
#   reading sources... [ 45%] index
#   reading sources... [ 54%] install
#   reading sources... [ 63%] man/fabio_viewer
#   reading sources... [ 72%] performances
#   reading sources... [ 81%] tutorials/Nexus2cbf
# Loaded extensions:
#   sphinx.ext.mathjax (1.7.9) from /usr/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.autodoc (1.7.9) from /usr/lib/python2.7/dist-packages/sphinx/ext/autodoc/__init__.pyc
#   alabaster (0.7.8) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   nbsphinx (0.2.9) from /usr/lib/python2.7/dist-packages/nbsphinx.pyc
#   sphinxcontrib.programoutput (unknown version) from /usr/lib/python2.7/dist-packages/sphinxcontrib/programoutput.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/setup_command.py", line 192, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 662, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/usr/lib/python2.7/dist-packages/sphinx/io.py", line 302, in read_doc
    pub.publish()
  File "/usr/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.7/dist-packages/nbsphinx.py", line 505, in parse
    nb = nbformat.reads(inputstring, as_version=_ipynbversion)
  File "/usr/lib/python2.7/dist-packages/nbformat/__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by kif** [comment]
unable to reproduce on another computer
