### ISSUE TITLE
Issue on Power9

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#312]
This is a linux-ppc64le-3.6
```
ERROR: testFullFormatName (fabio.test.testfabioconvert.TestFabioConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/test/testfabioconvert.py", line 135, in testFullFormatName
    image = fabio.open("output/03.npy")
  File "/home/test/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/openimage.py", line 159, in openimage
    obj = obj.read(obj.filename, frame)
  File "/home/test/workspace/fabio/build/lib.linux-ppc64le-3.6/fabio/numpyimage.py", line 161, in read
    self.dataset = numpy.load(infile)
  File "/home/test/venv-kieffer/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/test/venv-kieffer/lib/python3.6/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by vallsv** [comment]
Sounds like a numpy error? no?

**Comment by kif** [comment]
There is an error on the reading of tif files from pilatus using pillow. little polish is needed there
