### ISSUE TITLE
Tests failing with numpy 1.16.3

### ISSUE THREAD

**Issue by t20100** [silx-kit/fabio#313]
There is an issue while running `fabio` tests with `numpy` 1.16.3 (tested on both windows and linux with all python):

```
======================================================================
ERROR: testFullFormatName (fabio.test.testfabioconvert.TestFabioConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python3.4/site-packages/fabio/test/testfabioconvert.py", line 135, in testFullFormatName
    image = fabio.open("output/03.npy")
  File "/python3.4/site-packages/fabio/openimage.py", line 159, in openimage
    obj = obj.read(obj.filename, frame)
  File "/python3.4/site-packages/fabio/numpyimage.py", line 161, in read
    self.dataset = numpy.load(infile)
  File "/python3.4/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/python3.4/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

----------------------------------------------------------------------
```

Same test pass with numpy 1.15.0

**Comment by t20100** [comment]
Reproduced by re-running fabio CI: https://travis-ci.org/silx-kit/fabio/jobs/512908095

**Comment by t20100** [comment]
It was also working with 1.16.2... It seems to be broken only by v1.16.3.
