### ISSUE TITLE
convert from 'dm3' to 'cbf'

### ISSUE THREAD

**Issue by nguyen14ck** [silx-kit/fabio#334]
I got this error when trying to convert from 'dm3' to 'cbf' format.

System:
Ubuntu 19.04
Python 3.7
Fabio 0.9.0

Code:
```
fabio.open('test.dm3').convert('cbf').save('test.cbf')
```

Error:
```
Traceback (most recent call last):
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/user/.vscode-insiders/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Work/fabio/em2xray.py", line 66, in <module>
    em2xray(in_path, in_format, out_format)
  File "/home/user/Work/fabio/em2xray.py", line 37, in em2xray
    fb.convert(dest_format).save(dst_name)
  File "/home/user/anaconda3/lib/python3.7/site-packages/fabio/fabioimage.py", line 672, in save
    self.write(fname)
  File "/home/user/anaconda3/lib/python3.7/site-packages/fabio/cbfimage.py", line 336, in write
    out_file.write(self.cif.tostring(fname, "\r\n").encode("ASCII"))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 5318: ordinal not in range(128)
```
Thanks!

**Comment by kif** [comment]
You are right ...
Not all converter are available and the dm3 header contains some unicode characters which cannot be encoded in ASCII, here the `µ`.

I checked IUCr's page on CIF and the CBF header which is a CIF should only contain ASCII characters (not even all of them!) https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax

Moreover the data are often in float in DM3 and CBF is usually int32 ... Fabio implements only one of the 3 compression schemes possible and this compression requires integers.

All conversions are managed in https://github.com/silx-kit/fabio/blob/master/fabio/converters.py and dm3->cbf is not (yet) registered. 
If you need this conversion, you will have to decide what is an acceptable compromise. As you can see in the source code, there are already many formats which enforces the conversion of data to integers. For the unicode characters conversion you will also have to make choices. For example in another project I have a table like this to deal with the most common unicode characters for filename renaming:
https://github.com/kif/imagizer/blob/qt5/imagizer-src/encoding.py#L89 

Cheers,

**Comment by kif** [comment]
can we close the issue ?
