### ISSUE TITLE
[Error while building python-fabio]

### ISSUE THREAD

**Issue by alexmarie78** [silx-kit/fabio#353]
Hello, I am upgrading fabio debian's package.
When I run the command : 

```
dgit sbuild
```

in order to build the package, I get this error : 

```
INFO:fabio.setup:See the following execution of: /usr/bin/python3.8 /tmp/fabio_viewer_xm3krtiy --help
Traceback (most recent call last):
  File "/tmp/fabio_viewer_xm3krtiy", line 2, in <module>
    import fabio.app.viewer as app
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_fabio/build/fabio/app/viewer.py", line 49, in <module>
    from ._matplotlib import FigureCanvasQTAgg
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_fabio/build/fabio/app/_matplotlib.py", line 66, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg  # noqa
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 9, in <module>
    from matplotlib.backend_bases import _Backend
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "/usr/lib/python3/dist-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import cbook, dviread, font_manager, rcParams
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 48, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: cannot import name 'ft2font' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)
INFO:fabio.setup:Return code: 1
INFO:fabio.setup:See the following execution of: /usr/bin/python3.8 /tmp/fabio_viewer_xm3krtiy --version
Traceback (most recent call last):
  File "/tmp/fabio_viewer_xm3krtiy", line 2, in <module>
    import fabio.app.viewer as app
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_fabio/build/fabio/app/viewer.py", line 49, in <module>
    from ._matplotlib import FigureCanvasQTAgg
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_fabio/build/fabio/app/_matplotlib.py", line 66, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg  # noqa
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 9, in <module>
    from matplotlib.backend_bases import _Backend
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "/usr/lib/python3/dist-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import cbook, dviread, font_manager, rcParams
  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 48, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: cannot import name 'ft2font' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)
INFO:fabio.setup:Return code: 1
Traceback (most recent call last):
  File "setup.py", line 1068, in <module>
    setup_package()
  File "setup.py", line 1064, in setup_package
    setup(**setup_kwargs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 314, in run
    raise RuntimeError("Fail to generate '%s' man documentation" % target_name)
RuntimeError: Fail to generate 'fabio_viewer' man documentation
E: pybuild pybuild:341: build: plugin custom failed with: exit code=1: PYTHONPATH=/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_fabio/build xvfb-run -a --server-args="-screen 0 1024x768x24" python3.8 setup.py build_man
```

If you know how to investigate this, I will be glad to have your help ! 

Best,

Alexandre Marie

**Comment by vallsv** [comment]
Hi,

The first 2 exceptions looks to be problems in matlplotlib.

And I dont know about the last one.

Anyway i can't really help.

**Comment by alexmarie78** [comment]
In fact, it was a problem from Debian.
Matplotlib was not re-compiled in python 3.8 resulting in these issues.

**Comment by vallsv** [comment]
Then we can close it?

**Comment by alexmarie78** [comment]
Yes of course.
I close it.
