### ISSUE TITLE
Context error while using BytesIO as input

### ISSUE THREAD

**Issue by vallsv** [silx-kit/fabio#377]
Feedback from ID10.

They try to read edf from an archive.

Fabio is supposed to work with `ByteIO`, but a context manager looks broken.

```
with ZipFile(my_file,'r') as myzip:
for filename in myzip.namelist():
if filename.find(".edf") != -1:
print(filename)
#in_memory.write(myzip.read(filename))
in_memory = io.BytesIO(myzip.read(filename))
in_memory.seek(0)
print(in_memory.read())
in_memory.seek(0)
f = EdfFile.EdfFile(in_memory)
data = f.GetData()
#data = loadedf(in_memory)
print(data.shape)
plt.imshow(data,vmax=2)
plt.show()
raw_input()
exit()
```

```
Traceback (most recent call last):
File "./read_zip.py", line 71, in <module>
f = fabio.open(in_memory)
File "/users/chushkin/.local/lib/python2.7/site-packages/fabio/openimage.py", line 157, in openimage
obj = _openimage(filename)
File "/users/chushkin/.local/lib/python2.7/site-packages/fabio/openimage.py", line 200, in _openimage
with imo._open(actual_filename) as f:
AttributeError: BytesIO instance has no attribute '__exit__'
```

**Comment by vallsv** [comment]
Closed  by #378
