### ISSUE TITLE
ValueError: array to be byte-swapped is read-only

### ISSUE THREAD

**Issue by picca** [silx-kit/fabio#539]
Hello, I re-activated the test on Debian, and I get this error on the s390x architecture.

```
======================================================================
ERROR: testSC (fabio.test.test_compression.TestByteOffset.testSC)
test that datasets are unchanged after various compression/decompressions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_fabio/build/fabio/test/test_compression.py", line 101, in testSC
    obt_np = compression.decByteOffset_numpy(compression.compByteOffset_numpy(self.ds))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_fabio/build/fabio/compression/compression.py", line 243, in decByteOffset_numpy
    res.byteswap(True)
ValueError: array to be byte-swapped is read-only
```

**Comment by picca** [comment]
here the full log

https://buildd.debian.org/status/fetch.php?pkg=python-fabio&arch=s390x&ver=2023.6.0-2&stamp=1689880444&raw=0

it seems that BE architecture are all affected by this issue...

**Comment by picca** [comment]
the array is not writable because it does not own the data buffer...

maybe the best solution is just to set the newbyteorder before creating the array.

```
dt = np.dtype(int)
dt = dt.newbyteorder('>')
np.frombuffer(buf, dtype=dt) 
```

**Comment by kif** [comment]
Indeed, all big-endian architectures are likely to be affected in the same manner.

**Comment by kif** [comment]
Fixed in 542
