### ISSUE TITLE
Broken tests in python 3.12

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#544]
19 tests are failing under windows, they are all linked to this error message:
```
======================================================================
ERROR: test_read (fabio.test.codecs.test_dm3image.TestDm3Image.test_read)
check we can read dm3 images
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kieffer\workspace\fabio\build\Lib\site-packages\fabio\test\codecs\test_dm3image.py", line 73, in test_read
    obj1.read(fname)
  File "C:\Users\kieffer\workspace\fabio\build\Lib\site-packages\fabio\dm3image.py", line 125, in read
    self.read_tag_entry()
  File "C:\Users\kieffer\workspace\fabio\build\Lib\site-packages\fabio\dm3image.py", line 181, in read_tag_entry
    value = self.read_tag_type()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kieffer\workspace\fabio\build\Lib\site-packages\fabio\dm3image.py", line 214, in read_tag_type
    return self.readbytes(read_no_bytes, fmt, swap=self.swap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kieffer\workspace\fabio\build\Lib\site-packages\fabio\dm3image.py", line 145, in readbytes
    raw = self.infile.read(bytes_to_read)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python\3.12\Lib\gzip.py", line 324, in read
    return self._buffer.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python\3.12\Lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python\3.12\Lib\gzip.py", line 547, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

```

**Comment by kif** [comment]
There are several performance warning with recent cython/py312:
```
performance hint: fabio-git/src/fabio/ext/dense.pyx:136:30: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
```

**Comment by kif** [comment]
There are even 22 test failing on py312 under linux ...
