### ISSUE TITLE
`eiger2crysalis.py` does not support Eiger master files shipped by SPring8

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#596]
Reported by a PhD researcher at U. Tokyo

**Comment by khsacc** [comment]
Hi, thank you for dealing with the problem with SP8 data. 
I had errors, but the output Esperanto files seem OK. Probably this is because of local data processing at SPring-8: `pixel_mask` is removed from the master file to reduce data size, _cf._ https://github.com/keitaroyam/yamtbx/blob/master/doc/eiger-en.md#modification-on-masterh5-at-spring-8
I guess it is ok to ignore this, what do you think?

>  eiger2crysalis multi_100MGy_4_master.h5
Traceback (most recent call last):■■■■■■■■■■■■■■■ ]  98%  Exporting mask as CCD/SET file                                                                         
  File "/Users/hiroki/.pyenv/versions/3.10.3/bin/eiger2crysalis", line 8, in <module>
    sys.exit(main())
  File "/Users/hiroki/.pyenv/versions/3.10.3/lib/python3.10/site-packages/fabio/app/eiger2crysalis.py", line 619, in main
    converter.treat_mask(full=args.calc_mask)
  File "/Users/hiroki/.pyenv/versions/3.10.3/lib/python3.10/site-packages/fabio/app/eiger2crysalis.py", line 473, in treat_mask
    dstart = self.headers["dom_s"](0)
TypeError: 'float' object is not callable

**Comment by kif** [comment]
Normal "eiger-master" file contain not information about the goniometer:
You need to specify which axis rotate and at which speed, for example "--phi=2*index"
